version: "3.9"

services:
  backend:
    build: ./BE/app
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/app
      KEYCLOAK_URL: http://keycloak:8080
    depends_on:
      - db

  frontend:
    build: ./FE
    container_name: vue-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  pgdata: